//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu_DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANHSP
    {
        public int MaHA { get; set; }
        public Nullable<int> Masp { get; set; }
        public string URLAnh { get; set; }
        public Nullable<bool> AnhBia { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
