//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu_DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHIEUNAI
    {
        public int MaKN { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string PhanHoi { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
