//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu_DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CT_GIOHANG = new HashSet<CT_GIOHANG>();
            this.CT_HOADON = new HashSet<CT_HOADON>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.HINHANHSPs = new HashSet<HINHANHSP>();
            this.KHIEUNAIs = new HashSet<KHIEUNAI>();
            this.TINNHANs = new HashSet<TINNHAN>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<double> DanhGiaTB { get; set; }
        public Nullable<int> TongDanhGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_GIOHANG> CT_GIOHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANHSP> HINHANHSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHIEUNAI> KHIEUNAIs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINNHAN> TINNHANs { get; set; }
    }
}
